---
- id: npmjs:npm:node-fetch:1556
  title: Denial of Service
  description: |-
    Node Fetch did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure.

    For most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example: If you don't double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.
  affected_package: node-fetch
  vulnerable_versions:
  - "< 2.6.1"
  - ">= 3.0.0-beta.1 < 3.0.0-beta.9"
  severity: low
  package_manager: npm
  cve:
  - CVE-2020-15168
  cwe: CWE-400
  disclosed_date: 1970-01-01
  created_date: 1970-01-01
  last_modified_date: 1970-01-01
  credit: Unknown
- id: snykio:npm:node-fetch:674311
  title: Denial of Service
  description: |
    [node-fetch][1] is an A light-weight module that brings window.fetch to
    node.js

    Affected versions of this package are vulnerable to Denial of Service.
    Node Fetch did not honor the `size` option after following a redirect,
    which means that when a content size was over the limit, a FetchError
    would never get thrown and the process would end without failure.



    [1]: https://www.npmjs.com/package/node-fetch
  affected_package: node-fetch
  vulnerable_versions:
  - "<2.6.1"
  - ">=3.0.0-beta.1 <3.0.0-beta.9"
  severity: medium
  package_manager: npm
  cve:
  - CVE-2020-15168
  cwe:
  - CWE-400
  disclosed_date: 2020-09-10
  created_date: 2020-09-11
  last_modified_date: 2020-09-11
  credit:
  - Unknown
  references:
  - https://github.com/node-fetch/node-fetch/security/advisories/GHSA-w7rc-rwvf-8q5r
  source_url: https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311
