---
- id: snykio:pypi:pyyaml:42159
  title: Arbitrary Code Execution
  description: |
    [pyyaml][1] is a YAML parser and emitter for Python.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution due to using the insecure `yaml.load()` function.



    [1]: https://pypi.org/project/PyYAML/
  affected_package: pyyaml
  vulnerable_versions:
  - "< 4.2b1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2017-18342
  cwe:
  - CWE-94
  disclosed_date: 2017-08-26
  created_date: 2018-06-28
  last_modified_date: 2018-06-28
  credit:
  - Unknown
  references:
  - https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95
  - https://github.com/yaml/pyyaml/pull/74
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159
- id: snykio:pypi:pyyaml:550022
  title: Improper Access Control
  description: |
    [pyyaml][1] is a YAML parser and emitter for Python.

    Affected versions of this package are vulnerable to Improper Access
    Control. It has insufficient restrictions on the `load` and `load_all`
    functions because of a class deserialization issue, e.g., Popen is a
    class in the subprocess module.



    [1]: https://pypi.org/project/PyYAML/
  affected_package: pyyaml
  vulnerable_versions:
  - ">= 5.1 < 5.2"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-20477
  cwe:
  - CWE-284
  disclosed_date: 2020-02-19
  created_date: 2020-02-19
  last_modified_date: 2020-02-19
  credit:
  - Ashish Kukreti
  - Manmeet Singh
  references:
  - https://github.com/yaml/pyyaml/blob/master/CHANGES
  - https://github.com/yaml/pyyaml/issues/265
  - https://www.exploit-db.com/download/47655
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-550022
- id: snykio:pypi:pyyaml:559098
  title: Arbitrary Code Execution
  description: |
    [pyyaml][1] is a YAML parser and emitter for Python.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution. It is susceptible to arbitrary code execution when it
    processes untrusted YAML files through the `full_load` method or with
    the `FullLoader` loader. Applications that use the library to process
    untrusted input may be vulnerable to this flaw. An attacker could use
    this flaw to execute arbitrary code on the system by abusing the
    python/object/new constructor.



    [1]: https://pypi.org/project/PyYAML/
  affected_package: pyyaml
  vulnerable_versions:
  - ">= 0 < 5.3.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2020-1747
  cwe:
  - CWE-20
  disclosed_date: 2020-03-02
  created_date: 2020-03-02
  last_modified_date: 2020-03-02
  credit:
  - Riccardo Schirone (Red Hat)
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=1807367
  - https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0
  - https://github.com/yaml/pyyaml/pull/386
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098
