---
- id: ossindex:pypi:requests:361109
  title: "[CVE-2014-1829]  Information Exposure"
  description: Requests (aka python-requests) before 2.3.0 allows remote servers to
    obtain a netrc password by reading the Authorization header in a redirected request.
  affected_package: requests
  vulnerable_versions:
  - "<2.3.0"
  package_manager: pypi
  cve:
  - CVE-2014-1829
  disclosed_date: 2014-10-15
  created_date: 2014-10-15
  last_modified_date: 2017-01-16
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2014-0409.html
  - http://www.debian.org/security/2015/dsa-3146
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:133
  - http://www.ubuntu.com/usn/USN-2382-1
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108
  - https://github.com/kennethreitz/requests/issues/1885
  source_url: https://ossindex.net/resource/package/8401267383/vulnerabilities
- id: ossindex:pypi:requests:361110
  title: "[CVE-2014-1830]  Information Exposure"
  description: Requests (aka python-requests) before 2.3.0 allows remote servers to
    obtain sensitive information by reading the Proxy-Authorization header in a redirected
    request.
  affected_package: requests
  vulnerable_versions:
  - "<2.3.0"
  package_manager: pypi
  cve:
  - CVE-2014-1830
  disclosed_date: 2014-10-15
  created_date: 2014-10-15
  last_modified_date: 2017-01-16
  credit:
  - OSSIndex
  references:
  - http://advisories.mageia.org/MGASA-2014-0409.html
  - http://lists.opensuse.org/opensuse-updates/2016-01/msg00095.html
  - http://www.debian.org/security/2015/dsa-3146
  - http://www.mandriva.com/security/advisories?name=MDVSA-2015:133
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108
  - https://github.com/kennethreitz/requests/issues/1885
  source_url: https://ossindex.net/resource/package/8401267383/vulnerabilities
- id: snykio:pypi:requests:40023
  title: Denial of Service (DoS)
  description: |+
    [`requests`][1] is a Python HTTP for Humans.

    Affected versions of this package are vulnerable to Denial of Service
    attacks. Algorithmic complexity vulnerability in the
    `ssl.match_hostname` function in Python 3.2.x, 3.3.x, and earlier, and
    unspecified versions of `python-backports-ssl_match_hostname` as used
    for older Python versions, allows remote attackers to cause a denial of
    service (CPU consumption) via multiple wildcard characters in the common
    name in a certificate.



    [1]: https://pypi.python.org/pypi/requests
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: requests
  vulnerable_versions:
  - "< 1.1.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-2099
  cwe:
  - CWE-399
  disclosed_date: 2013-05-15
  created_date: 2013-05-15
  last_modified_date: 2013-05-15
  credit:
  - Florian Weimer
  references:
  - http://bugs.python.org/issue17980
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2099
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40023
- id: snykio:pypi:requests:40030
  title: Information Exposure
  description: |
    [`requests`][1] is a Python HTTP for Humans.

    Affected versions of this package are vulnerable to Information
    Exposure. Remote servers may obtain a netrc password by reading the
    Authorization header in a redirected request.



    [1]: https://pypi.python.org/pypi/requests
  affected_package: requests
  vulnerable_versions:
  - "< 2.3.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2014-1829
  cwe:
  - CWE-200
  disclosed_date: 2013-12-25
  created_date: 2013-12-25
  last_modified_date: 2013-12-25
  credit:
  - Jakub Wilk
  references:
  - https://bugzilla.redhat.com/CVE-2014-1829
  - https://github.com/kennethreitz/requests/commit/f1893c835570d72823c970fbd6e0e42c13b1f0f2
  - https://github.com/kennethreitz/requests/issues/1885
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40030
- id: snykio:pypi:requests:40031
  title: Information Exposure
  description: |
    [`requests`][1] is a Python HTTP for Humans.

    Affected versions of this package are vulnerable to Information
    Disclosure attacks. Remote servers may obtain sensitive information by
    reading the `Proxy-Authorization` header in a redirected request.



    [1]: https://pypi.python.org/pypi/requests
  affected_package: requests
  vulnerable_versions:
  - "< 2.3.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2014-1830
  cwe:
  - CWE-200
  disclosed_date: 2013-12-25
  created_date: 2013-12-25
  last_modified_date: 2013-12-25
  credit:
  - Jakub Wilk
  references:
  - https://bugzilla.redhat.com/CVE-2014-1830
  - https://github.com/kennethreitz/requests/commit/4d8cb3244e8e4f84b250c10a48e025f9a8bf6137
  - https://github.com/kennethreitz/requests/issues/1885#issuecomment-33793651
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40031
- id: snykio:pypi:requests:40316
  title: Session Fixation
  description: |
    [`requests`][1] is a Python HTTP for Humans.

    The `resolve_redirects` function in sessions.py in requests 2.1.0
    through 2.5.3 allows remote attackers to conduct session fixation
    attacks via a cookie without a host value in a redirect.



    [1]: https://pypi.python.org/pypi/requests
  affected_package: requests
  vulnerable_versions:
  - ">= 2.1.0 < 2.6.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2015-2296
  cwe:
  - CWE-384
  disclosed_date: 2015-03-14
  created_date: 2015-03-14
  last_modified_date: 2015-03-14
  credit:
  - Matthew Daley
  references:
  - http://www.openwall.com/lists/oss-security/2015/03/14/4
  - https://github.com/kennethreitz/requests/commit/3bd8afbff29e50b38f889b2f688785a669b9aafc
  - https://warehouse.python.org/project/requests/2.6.0/
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-2296
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40316
- id: snykio:pypi:requests:40470
  title: HTTP Request Redirection
  description: |
    [`requests`][1] is a Python HTTP for Humans.

    Affected versions of this package are vulnerable to HTTPoxy attacks. The
    Python `CGIHandler` class did not properly protect against the
    `HTTP_PROXY` variable. A remote attacker could possibly use this flaw to
    redirect HTTP requests performed by a Python CGI script to an
    attacker-controlled proxy via a malicious HTTP request.



    [1]: https://pypi.python.org/pypi/requests
  affected_package: requests
  vulnerable_versions:
  - ">= 1.2.0 < 2.10.1"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-601
  disclosed_date: 2016-07-17
  created_date: 2016-07-17
  last_modified_date: 2016-07-17
  credit:
  - Scott Geary
  references:
  - https://github.com/requests/requests/issues/3422
  - https://httpoxy.org/
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40470
- id: snykio:pypi:requests:40480
  title: Denial of Service (DoS)
  description: |+
    [`requests`][1] is a Python HTTP for Humans.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS) attacks. When sending a digest with an incorrect password, it will
    retry the request for infinity. An attacker can send many of these
    requests, causing a denial of service.



    [1]: https://pypi.python.org/pypi/requests
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: requests
  vulnerable_versions:
  - "<= 1.2.3"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-400
  disclosed_date: 2012-04-07
  created_date: 2012-04-07
  last_modified_date: 2012-04-07
  credit:
  - Unknown
  references:
  - https://github.com/requests/requests/issues/541
  - https://github.com/requests/requests/pull/547
  - https://github.com/requests/requests/pull/547/commits/c3e6c41fc164d4348f8ce197bd0075aff05637af
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40480
- id: snykio:pypi:requests:72435
  title: Information Exposure
  description: |
    [Requests][1] is a *Non-GMO* HTTP library for Python

    Affected versions of this package are vulnerable to Information
    Exposure. Upon receiving a same-hostname https-to-http redirect, it
    sends the HTTP Authorization header to an http URI. This makes it easier
    for remote attackers to discover credentials by sniffing the network.



    [1]: https://pypi.org/project/requests/
  affected_package: requests
  vulnerable_versions:
  - "< 2.20"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2018-18074
  cwe:
  - CWE-200
  disclosed_date: 2018-10-09
  created_date: 2018-10-10
  last_modified_date: 2018-10-10
  credit:
  - Unknown
  references:
  - https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff
  - https://github.com/requests/requests/issues/4716
  - https://github.com/requests/requests/pull/4718
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435
- id: victims:pypi:requests:2013-2099
  title: ssl.match_hostname() DoS via certificates
  affected_package: requests
  vulnerable_versions:
  - "<=1.0.3"
  patched_versions:
  - ">=1.1.0"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2013-2099
  cvss_v2_score: 2.6
  credit:
  - Victims CVE Database
  references:
  - http://bugs.python.org/issue17980
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-2099
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2013/2099.yaml
- id: victims:pypi:requests:2014-1829
  title: 'python-requests: Authorization header leak'
  affected_package: requests
  vulnerable_versions:
  - "<=2.2.1"
  patched_versions:
  - ">=2.3.0"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2014-1829
  cvss_v2_score: 2.6
  credit:
  - Victims CVE Database
  references:
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108
  - https://bugzilla.redhat.com/CVE-2014-1829
  - https://github.com/kennethreitz/requests/commit/f1893c835570d72823c970fbd6e0e42c13b1f0f2
  - https://github.com/kennethreitz/requests/issues/1885
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/1829.yaml
- id: victims:pypi:requests:2014-1830
  title: 'python-requests: Proxy-Authorization header leak'
  affected_package: requests
  vulnerable_versions:
  - "<=2.2.1"
  patched_versions:
  - ">=2.3.0"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2014-1830
  cvss_v2_score: 2.6
  credit:
  - Victims CVE Database
  references:
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108
  - https://bugzilla.redhat.com/CVE-2014-1830
  - https://github.com/kennethreitz/requests/commit/4d8cb3244e8e4f84b250c10a48e025f9a8bf6137
  - https://github.com/kennethreitz/requests/issues/1885#issuecomment-33793651
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2014/1830.yaml
