---
- id: snykio:pypi:tensorflow:451636
  title: Buffer Overflow
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Buffer Overflow. A
    malicious user could pass a malformed version of a `TFLite` graph into
    `TOCO` will cause `TOCO` to crash or cause a buffer overflow,
    potentially allowing malicious code to be executed.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - ">= 1.5.0 < 1.7.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2018-8825
  cwe:
  - CWE-121
  disclosed_date: 2019-04-23
  created_date: 2019-04-25
  last_modified_date: 2019-04-25
  credit:
  - Blade Team of Tencent
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-003.md
  - https://github.com/tensorflow/tensorflow/commit/41335abb46f80ca644b5738550daef6136ba5476
  - https://github.com/tensorflow/tensorflow/commit/8badd11d875a826bd318ed439909d5c47a7fb811
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-451636
- id: snykio:pypi:tensorflow:451669
  title: Denial of Service (DoS)
  description: |+
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS). It was possible to pass a `null` value into `strcat` when parsing
    a GIF, causing DoS attacks.



    [1]: https://pypi.org/project/tensorflow/
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: tensorflow
  vulnerable_versions:
  - "< 1.6.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2018-7576
  cwe:
  - CWE-400
  disclosed_date: 2019-04-23
  created_date: 2019-07-21
  last_modified_date: 2019-07-21
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-002.md
  - https://github.com/tensorflow/tensorflow/commit/c48431588e7cf8aff61d4c299231e3e925144df8
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-451669
- id: snykio:pypi:tensorflow:451670
  title: Buffer Overflow
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Buffer Overflow when
    parsing a malicious meta checkpoint, resulting in an out of bounds read.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - ">= 1.0.0 < 1.7.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2018-7575
  cwe:
  - CWE-190
  disclosed_date: 2019-04-24
  created_date: 2019-07-21
  last_modified_date: 2019-07-21
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-004.md
  - https://github.com/tensorflow/tensorflow/commit/2006ef57602012939dc10d7e8961925b320d3ef6
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-451670
- id: snykio:pypi:tensorflow:451671
  title: Out-of-bounds Read
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Out-of-bounds Read.
    A malicious user could crash the process or gain access to unintended
    regions of the process memory.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - "< 1.7.0"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2018-7574
  cwe:
  - CWE-125
  disclosed_date: 2019-04-24
  created_date: 2019-07-21
  last_modified_date: 2019-07-21
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-001.md
  - https://github.com/tensorflow/tensorflow/commit/49f73c55d56edffebde4bca4a407ad69c1cae433
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-451671
- id: snykio:pypi:tensorflow:451681
  title: Buffer Overflow
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Buffer Overflow. It
    could cause a crash or read from other parts of process memory via a
    crafted configuration file.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - ">= 1.1.0 < 1.7.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2018-10055
  cwe:
  - CWE-119
  disclosed_date: 2019-04-24
  created_date: 2019-07-22
  last_modified_date: 2019-07-22
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2018-006.md
  - https://github.com/tensorflow/tensorflow/commit/c89ab82a82585cdaa90bf4911980e9e845909e78
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-451681
- id: snykio:pypi:tensorflow:537867
  title: Heap-based Buffer Overflow
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Heap-based Buffer
    Overflow via `UnsortedSegmentSum`. When the Index template argument is
    int32 `data_size` and `num_segments` fields are truncated from int64 to
    int32 and can produce negative numbers, resulting in accessing out of
    bounds heap memory.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - "< 1.15"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2019-16778
  cwe:
  - CWE-122
  disclosed_date: 2019-12-16
  created_date: 2019-12-17
  last_modified_date: 2019-12-17
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2019-002.md
  - https://github.com/tensorflow/tensorflow/commit/db4f9717c41bccc3ce10099ab61996b246099892
  - https://github.com/tensorflow/tensorflow/security/advisories/GHSA-844w-j86r-4x2j
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-537867
- id: snykio:pypi:tensorflow:543629
  title: Denial of Service (DoS)
  description: |+
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS). Converting a string (from Python) to a `tf.float16` value results
    in a segmentation fault in eager mode as the format checks for this use
    case are only in the graph mode. A malicious attacker can send a data
    point which contains a string instead of a `tf.float16` value. Similar
    effects can be obtained by manipulating saved models and checkpoints
    whereby replacing a scalar `tf.float16` value with a scalar string will
    trigger this issue due to automatic conversions.



    [1]: https://pypi.org/project/tensorflow/
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: tensorflow
  vulnerable_versions:
  - ">= 1.12.0 < 1.15.2"
  - ">= 2.0.0a0 < 2.0.1"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2020-5215
  cwe:
  - CWE-400
  disclosed_date: 2020-01-28
  created_date: 2020-01-29
  last_modified_date: 2020-01-29
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/commit/5ac1b9e24ff6afc465756edf845d2e9660bd34bf
  - https://github.com/tensorflow/tensorflow/releases/tag/v1.15.2
  - https://github.com/tensorflow/tensorflow/releases/tag/v2.0.1
  - https://github.com/tensorflow/tensorflow/security/advisories/GHSA-977j-xj7q-2jr9
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-543629
- id: snykio:pypi:tensorflow:564349
  title: NULL Pointer Dereference
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to NULL Pointer
    Dereference. A carefully crafted GIF images can produce a null pointer
    dereference during decoding.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - "< 1.12.2"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-476
  disclosed_date: 2020-04-01
  created_date: 2020-04-01
  last_modified_date: 2020-04-01
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/622a516e710e249ddc65a8a977ff1ae78b4d2e4d/RELEASE.md#release-1122
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-564349
- id: snykio:pypi:tensorflow:564351
  title: Out-of-bounds Read
  description: |
    [tensorflow][1] is a machine learning framework.

    Affected versions of this package are vulnerable to Out-of-bounds Read.
    Decoding variant tensors from proto could result in heap out of bounds
    memory access.



    [1]: https://pypi.org/project/tensorflow/
  affected_package: tensorflow
  vulnerable_versions:
  - "< 2.0.0"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-125
  disclosed_date: 2019-09-30
  created_date: 2020-04-01
  last_modified_date: 2020-04-01
  credit:
  - Unknown
  references:
  - https://github.com/tensorflow/tensorflow/blob/622a516e710e249ddc65a8a977ff1ae78b4d2e4d/RELEASE.md#release-200
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TENSORFLOW-564351
