---
- id: snykio:pypi:typed_ast:535627
  title: Out-of-bounds Read
  description: |
    [typed\_ast][1] is a Python 3 package that provides a Python 2.7 and
    Python 3 parser similar to the standard ast library.

    Affected versions of this package are vulnerable to Out-of-bounds Read
    via `handle_keywordonly_args`. An attacker with the ability to cause a
    Python interpreter to parse Python source (but not necessarily execute
    it) may be able to crash the interpreter process.



    [1]: https://github.com/python/typed_ast
  affected_package: typed_ast
  vulnerable_versions:
  - ">= 1.30 < 1.32"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-19274
  cwe:
  - CWE-125
  disclosed_date: 2019-11-26
  created_date: 2019-11-26
  last_modified_date: 2019-11-26
  credit:
  - Brad Larsen
  references:
  - https://bugs.python.org/issue36495
  - https://github.com/python/typed_ast/commit/156afcb26c198e162504a57caddfe0acd9ed7dce
  - https://github.com/python/typed_ast/commit/dc317ac9cff859aa84eeabe03fb5004982545b3b
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TYPEDAST-535627
- id: snykio:pypi:typed_ast:535628
  title: Out-of-bounds Read
  description: |
    [typed\_ast][1] is a Python 3 package that provides a Python 2.7 and
    Python 3 parser similar to the standard ast library.

    Affected versions of this package are vulnerable to Out-of-bounds Read
    via `ast_for_arguments` out-of-bounds read. An attacker with the ability
    to cause a Python interpreter to parse Python source (but not
    necessarily execute it) may be able to crash the interpreter process.
    This could be a concern, for example, in a web-based service that parses
    (but does not execute) Python.



    [1]: https://github.com/python/typed_ast
  affected_package: typed_ast
  vulnerable_versions:
  - ">= 1.30 < 1.32"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-19275
  cwe:
  - CWE-125
  disclosed_date: 2019-11-26
  created_date: 2019-11-26
  last_modified_date: 2019-11-26
  credit:
  - Brad Larsen
  references:
  - https://bugs.python.org/issue36495
  - https://github.com/python/typed_ast/commit/156afcb26c198e162504a57caddfe0acd9ed7dce
  - https://github.com/python/typed_ast/commit/dc317ac9cff859aa84eeabe03fb5004982545b3b
  source_url: https://snyk.io/vuln/SNYK-PYTHON-TYPEDAST-535628
